name: Guess The Number Game

on:
  push:
    branches:
      - main # Or 'master', depending on your default branch name

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to get full commit history for messages

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Get latest commit message
        id: get_commit_message
        run: |
          echo "GITHUB_COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
        
      - name: Run Guess Game Script
        run: python game/main.py

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md guesses.log
          # Only commit if there are changes
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Update Guess The Number Game Status"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is automatically provided by GitHub Actions